name: PumpkinEventos
version: '${version}'
main: pumpkin.eventos.PumpkinEventos
api-version: '1.21'
folia-supported: false
author: Pumpkingz
description: Core avanzado de eventos para Pumpkin Network. Soporta TNT Games, Simon Dice y El Suelo es Lava.

# Dependencias necesarias para que el plugin arranque
depend:
  - LuckPerms
  - GSit
  - AdvancedSlimePaper
softdepend:
  - PlaceholderAPI
  - LibsDisguises

commands:
  evento:
    description: Comando principal de administración del core de eventos.
    permission: pumpkin.admin
    aliases: [eventos, ev]
  votar:
    description: Comando para que los jugadores voten por el siguiente minijuego.
    usage: /votar <juego>
  gamemode:
    description: Cambia el modo de juego.
    permission: pumpkin.command.gamemode
    aliases: [gm]
  gmc:
    description: Creative mode.
    permission: pumpkin.command.gamemode
  gms:
    description: Survival mode.
    permission: pumpkin.command.gamemode
  gma:
    description: Adventure mode.
    permission: pumpkin.command.gamemode
  gmsp:
    description: Spectator mode.
    permission: pumpkin.command.gamemode
  puntaje:
    description: "Sistema de puntajes del servidor"
    aliases: [puntos, score]
  espectear:
    description: Vuelve al mapa del evento como espectador.
  arena:
    description: Comandos de administración de arenas.
    permission: pumpkin.admin
  pvote:
    description: Votar por un efecto de poción.
    usage: /pvote <efecto>
  pvpvote:
    description: Votar por PvP (si/no).
    usage: /pvpvote <si|no>
  # --- COMANDOS DE EXTRAS ---
  extras:
    description: Comando para forzar desastres o iniciar votaciones de extras.
    permission: pumpkin.evento.extras
    usage: /extras <start|startall|vote>
  evote:
    description: Comando interno para votar por un desastre.
    usage: /evote <desastre>

permissions:
  pumpkin.admin:
    description: Acceso total al core de eventos.
    default: op
  pumpkin.command.gamemode:
    description: Permite usar comandos de modo de juego.
    default: op
  # Permisos específicos para Staff/Hosts
  pumpkin.evento.iniciar:
    description: Permite iniciar y detener juegos.
    default: op
  pumpkin.evento.votacion:
    description: Permite lanzar la votación de minijuegos.
    default: op
  pumpkin.evento.ruleta:
    description: Permite usar la ruleta de selección de juegos.
    default: op
  pumpkin.evento.extras:
    description: Permite gestionar desastres y extras.
    default: op
